### ISSUE TITLE
Error installing pin

### ISSUE THREAD

**Issue by Zearin** [dustinlacewell/pin#3]
Just tried installing via `pip`, but got the following error:

```
pip --verbose install pin
Downloading/unpacking pin
  Running setup.py egg_info for package pin
    Traceback (most recent call last):
      File "<string>", line 14, in <module>
      File "/Users/<my-username>/build/pin/setup.py", line 5, in <module>
        from pin import VERSION
      File "pin/__init__.py", line 9, in <module>
        from straight.plugin import load as pluginloader
    ImportError: No module named straight.plugin
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):

  File "<string>", line 14, in <module>

  File "/Users/<my-username>/build/pin/setup.py", line 5, in <module>

    from pin import VERSION

  File "pin/__init__.py", line 9, in <module>

    from straight.plugin import load as pluginloader

ImportError: No module named straight.plugin

----------------------------------------
Command python setup.py egg_info failed with error code 1
Exception information:
Traceback (most recent call last):
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/basecommand.py", line 126, in main
    self.run(options, args)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/commands/install.py", line 223, in run
    requirement_set.prepare_files(finder, force_root_egg_info=self.bundle, bundle=self.bundle)
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req.py", line 986, in prepare_files
    req_to_install.run_egg_info()
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/req.py", line 222, in run_egg_info
    command_desc='python setup.py egg_info')
  File "/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/pip/__init__.py", line 255, in call_subprocess
    % (command_desc, proc.returncode))
InstallationError: Command python setup.py egg_info failed with error code 1

Storing complete log in /Users/<my-username>/.pip/pip.log
```

Running Python 2.7 on Mac OS X 10.6.8.

**Comment by dustinlacewell** [comment]
Yeah, pin requires straight.plugin, there is a pull request to lazy load it. I'll accept it.

**Comment by dustinlacewell** [comment]
Merge done, you can try to verify that this was fixed.
